services:
  anisette:
    image: dadoum/anisette-v3-server
    container_name: anisette
    restart: always
    volumes:
      - anisette-v3_data:/home/Alcoholic/.config/anisette-v3/lib/
    networks:
      - mh-network

  macless-haystack:
    container_name: macless-haystack
    build:
      context: ./endpoint
      dockerfile: macless-haystack.prod.dockerfile
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - mh_data:/app/data
    networks:
      - mh-network
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mh.entrypoints=web"
      - "traefik.http.routers.mh.rule=Host(`mh.dev.0x08.in`)"
      - "traefik.http.routers.mh.service=mh-svc"
      - "traefik.http.services.mh-svc.loadbalancer.server.port=6176"
    depends_on:
      - anisette


networks:
  mh-network:
    driver: bridge
  traefik:
    external: true

volumes:
  anisette-v3_data:
  mh_data:
