version: '3.8'

services:
  anisette:
    image: dadoum/anisette-v3-server
    container_name: anisette
    restart: always
    volumes:
      - anisette-v3_data:/home/Alcoholic/.config/anisette-v3/lib/

  macless-haystack:
    container_name: macless-haystack
    build:
      context: ./endpoint
      dockerfile: macless-haystack.prod.dockerfile
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - mh_data:/app/data
    depends_on:
      - anisette

  macless-haystack-frontend:
    container_name: macless-haystack-frontend
    build:
      context: ./macless_haystack
      dockerfile: macless-haystack-frontend.prod.dockerfile
    restart: unless-stopped

volumes:
  anisette-v3_data:
  mh_data:
